home:
    pattern:  /
    defaults: { _controller: AnimeDBCatalogBundle:Home:index }

home_search:
    pattern:  /search.html
    defaults: { _controller: AnimeDBCatalogBundle:Home:search }

home_search_simple_form:
    pattern:  /search-simple-form.html
    defaults: { _controller: AnimeDBCatalogBundle:Home:searchSimpleForm }

home_autocomplete_name:
    pattern:  /autocomplete-name.json
    defaults: { _controller: AnimeDBCatalogBundle:Home:autocompleteName, _format: json }


item_add:
    pattern:  /add.html
    defaults: { _controller: AnimeDBCatalogBundle:Item:add }

item_add_manually:
    pattern:  /add-manually.html
    defaults: { _controller: AnimeDBCatalogBundle:Item:addManually }

item_show:
    pattern:  /{id}-{name}/
    defaults: { _controller: AnimeDBCatalogBundle:Item:show }
    requirements:
        id:  \d+

item_change:
    pattern:  /{id}-{name}/change.html
    defaults: { _controller: AnimeDBCatalogBundle:Item:change }
    requirements:
        id:  \d+

item_remove:
    pattern:  /{id}-{name}/remove.html
    defaults: { _controller: AnimeDBCatalogBundle:Item:remove }
    requirements:
        id:  \d+

item_complement:
    pattern:  /{id}-{name}/complement.html
    defaults: { _controller: AnimeDBCatalogBundle:Item:complement }
    requirements:
        id:  \d+


filler_search:
    pattern:  /filler/search.html
    defaults: { _controller: AnimeDBCatalogBundle:Filler:search }

filler_fill:
    pattern:  /filler/fill.html
    defaults: { _controller: AnimeDBCatalogBundle:Filler:fill }


media_favicon:
    pattern:  /media/favicon/{host}.ico
    requirements:
        host: .+
    defaults: { _controller: AnimeDBCatalogBundle:Media:favicon }


form_template:
    pattern:  /form/template/{template}.html
    requirements:
        template: "[-a-z]+"
    defaults: { _controller: AnimeDBCatalogBundle:Form:template }

form_local_path:
    pattern:  /form/local_path.html
    defaults: { _controller: AnimeDBCatalogBundle:Form:localPath }

form_local_path_folders:
    pattern:  /form/local_path/folders.json
    defaults: { _controller: AnimeDBCatalogBundle:Form:localPathFolders, _format: json }


form_image:
    pattern:  /form/image.html
    defaults: { _controller: AnimeDBCatalogBundle:Form:image }

form_image_upload:
    pattern:  /form/imageUpload.json
    defaults: { _controller: AnimeDBCatalogBundle:Form:imageUpload, _format: json }
    requirements:
        _method:  POST
